version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: order_day_of_week
        tests:
          - accepted_values:
              arguments:
                values: [0, 1, 2, 3, 4, 5, 6]

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
